### ISSUE TITLE
Panic if href field doesn't exist at root

### ISSUE THREAD

**Issue by minodisk** [go-jstmpl/go-jstmpl#8]
Check `hs.Schema.Extras["href"]` isn't `nil` at:

https://github.com/go-jstmpl/go-jstmpl/blob/1f57c13497d6fe96297add1e639f5756b61125be/builder.go#L28

**Comment by meta-closure** [comment]
https://github.com/go-jstmpl/go-jstmpl/pull/12/commits/c8ccb3dece4f0fb24f628c88cdbf066cc9a400a4

href nil check add

**Comment by meta-closure** [comment]
https://github.com/go-jstmpl/go-jstmpl/pull/12
